# Generated by Django 5.2.8 on 2025-11-13 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('visaType', models.CharField(blank=True, max_length=50)),
                ('personCount', models.PositiveIntegerField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, null=True)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paymentStatus', models.CharField(blank=True, max_length=30)),
                ('saleNotes', models.TextField(blank=True)),
                ('saleDate', models.DateTimeField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
